In [11]:
import pandas as pd

In [52]:
# key_word = "production waste OR chemical waste OR toxic waste OR reason of waste OR us waste problem OR us bad waste system problem OR us environment waste problem"
key_word = "us environment waste problem"
token = ""

filename_template = "2023_month_{month}_uewp.csv"
search_template = key_word + ' until:{end_date} since:{start_date} lang:en'

# Define months and days
months = [
    {"month": "01", "start_date": "2023-01-01", "end_date": "2023-01-31"},
    {"month": "02", "start_date": "2023-02-01", "end_date": "2023-02-28"},
    {"month": "03", "start_date": "2023-03-01", "end_date": "2023-03-31"},
    {"month": "04", "start_date": "2023-04-01", "end_date": "2023-04-30"},
    {"month": "05", "start_date": "2023-05-01", "end_date": "2023-05-31"},
    {"month": "06", "start_date": "2023-06-01", "end_date": "2023-06-30"},
    {"month": "07", "start_date": "2023-07-01", "end_date": "2023-07-31"},
    {"month": "08", "start_date": "2023-08-01", "end_date": "2023-08-31"},
    {"month": "09", "start_date": "2023-09-01", "end_date": "2023-09-30"},
    {"month": "10", "start_date": "2023-10-01", "end_date": "2023-10-31"},
    {"month": "11", "start_date": "2023-11-01", "end_date": "2023-11-30"},
    {"month": "12", "start_date": "2023-12-01", "end_date": "2023-12-31"},
]

commands = []
for m in months:
    filename = filename_template.format(month=m["month"])
    search_keyword = search_template.format(
        end_date=m["end_date"], start_date=m["start_date"]
    )
    command = f'npx --yes tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" -l {3000} --token "{token}"'
    commands.append(command)

# Print the commands for manual execution
for cmd in commands:
    print(cmd)
print()

npx --yes tweet-harvest@2.6.1 -o "2023_month_01_uewp.csv" -s "us environment waste problem until:2023-01-31 since:2023-01-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_02_uewp.csv" -s "us environment waste problem until:2023-02-28 since:2023-02-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_03_uewp.csv" -s "us environment waste problem until:2023-03-31 since:2023-03-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_04_uewp.csv" -s "us environment waste problem until:2023-04-30 since:2023-04-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_05_uewp.csv" -s "us environment waste problem until:2023-05-31 since:2023-05-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_06_uewp.csv" -s "us environment waste problem until:2023-06-30 since:2023-06-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_07_uewp.csv" -s "us environment waste problem until:2023-07-31 since:2023-07-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_08_uewp.csv" -s "us environment waste problem until:2023-08-31 since:2023-08-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_09_uewp.csv" -s "us environment waste problem until:2023-09-30 since:2023-09-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_10_uewp.csv" -s "us environment waste problem until:2023-10-31 since:2023-10-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_11_uewp.csv" -s "us environment waste problem until:2023-11-30 since:2023-11-01 lang:en" -l 3000 --token ""
npx --yes tweet-harvest@2.6.1 -o "2023_month_12_uewp.csv" -s "us environment waste problem until:2023-12-31 since:2023-12-01 lang:en" -l 3000 --token ""

In [48]:
import os
tweets_dir = "tweets-data"
tweets = [os.path.join(tweets_dir, file) for file in os.listdir(tweets_dir) if file.endswith('.csv')]

df = pd.concat([pd.read_csv(tweet) for tweet in tweets])
df = df[['created_at', 'full_text']].reset_index(drop=True)
df['created_at'] = pd.to_datetime(df['created_at'])
df = df.sort_values(by='created_at').reset_index(drop=True)
df

C:\Users\rhafaelc\AppData\Local\Temp\ipykernel_30908\2488500990.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['created_at'] = pd.to_datetime(df['created_at'])

,created_at,full_text
0,2023-01-01 04:30:30+00:00,Condom crisis: Busia sex workers recycle condo...
1,2023-01-01 04:47:16+00:00,Cause we know crying doesn t solve the problem...
2,2023-01-01 06:42:04+00:00,Obviously it s bad for your health but it s al...
3,2023-01-01 06:42:04+00:00,Obviously it s bad for your health but it s al...
4,2023-01-01 06:42:04+00:00,Obviously it s bad for your health but it s al...
...,...,...
13330,2023-12-30 22:27:09+00:00,Pilots are being paid per pound of industrial ...
13331,2023-12-30 22:59:50+00:00,toxic waste ain't that sour tbh
13332,2023-12-30 23:00:32+00:00,This eye-opening ArcGIS StoryMap provides an o...
13333,2023-12-30 23:35:08+00:00,There is no situation where not giving up is t...
13334,2023-12-30 23:59:55+00:00,@gimbakakanda education is a waste if this is ...

In [49]:
df.drop_duplicates(subset=['full_text'], keep='first', inplace=True)
df.reset_index(drop=True, inplace=True)

In [50]:
df.to_csv('tweets-2023.csv', index=False)

In [51]:
df

,created_at,full_text
0,2023-01-01 04:30:30+00:00,Condom crisis: Busia sex workers recycle condo...
1,2023-01-01 04:47:16+00:00,Cause we know crying doesn t solve the problem...
2,2023-01-01 06:42:04+00:00,Obviously it s bad for your health but it s al...
3,2023-01-01 06:42:05+00:00,Vapes can take hundreds of years to degrade. T...
4,2023-01-01 09:48:10+00:00,Aluminium crushing: If the manufacturer finds ...
...,...,...
9880,2023-12-30 22:27:09+00:00,Pilots are being paid per pound of industrial ...
9881,2023-12-30 22:59:50+00:00,toxic waste ain't that sour tbh
9882,2023-12-30 23:00:32+00:00,This eye-opening ArcGIS StoryMap provides an o...
9883,2023-12-30 23:35:08+00:00,There is no situation where not giving up is t...
9884,2023-12-30 23:59:55+00:00,@gimbakakanda education is a waste if this is ...